---
services:
- redis-server
sudo: false
language: ruby
cache: bundler
rvm:
- jruby-1.7.25
jdk: oraclejdk8
script:
- bundle exec rspec spec --order rand
- bundle exec rspec spec --order rand -t redis
before_install: []
